import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { FaArrowLeft, FaCheck, FaDownload, FaPlus, FaSave, FaSearch, FaShieldAlt, FaTint, FaTruck, FaUserPlus } from "react-icons/fa";
import { useAppState } from "../context/useAppState";
import StatusBadge from "../components/StatusBadge";
import { normaliseRole, roleLabels, ROLES } from "../utils/roles";
import { exportToCsv } from "../utils/exportUtils";

const catalog = {
  "/admin/users": { title: "User Management", description: "Create, review, activate and manage UMULOPA user accounts.", action: "Add user" },
  "/admin/roles": { title: "Role Management", description: "Review role assignments and access boundaries." },
  "/admin/hospitals": { title: "Hospital Network", description: "Manage facilities connected to the UMULOPA network.", action: "Add hospital" },
  "/admin/permissions": { title: "Permissions", description: "Review permission bundles and access controls." },
  "/admin/audit-logs": { title: "Audit Logs", description: "Trace important administrative and operational events." },
  "/admin/reports": { title: "Platform Reports", description: "Generate and export platform-level operational reports." },
  "/admin/system-health": { title: "System Health", description: "Monitor application services and integration health." },
  "/admin/settings": { title: "Administrator Settings", description: "Manage platform preferences and security controls." },
  "/admin/backup": { title: "Backup & Recovery", description: "Run a frontend workflow for backup records and recovery checks." },
  "/regional/inventory": { title: "Regional Blood Inventory", description: "Monitor, adjust and export regional stock." },
  "/regional/distribution": { title: "Blood Distribution", description: "Allocate available units to approved hospital requests." },
  "/regional/hospitals": { title: "Regional Hospitals", description: "Review hospital stock and operational status." },
  "/regional/emergency": { title: "Emergency Requests", description: "Prioritise and respond to urgent blood requirements." },
  "/regional/transfers": { title: "Blood Transfers", description: "Create, dispatch and complete blood transfer workflows." },
  "/regional/analytics": { title: "Regional Analytics", description: "Review demand, stock and fulfilment indicators." },
  "/regional/reports": { title: "Regional Reports", description: "Generate regional reports from current application state." },
  "/regional/settings": { title: "Regional Settings", description: "Configure regional operating preferences." },
  "/staff/emergency": { title: "Emergency Cases", description: "Coordinate urgent patient blood requests and escalation." },
  "/donor/donate": { title: "Donate Blood", description: "Record a donor's intention to donate and create an appointment workflow." },
  "/donor/appointments": { title: "Appointments", description: "Book, confirm and cancel donor appointments." },
  "/donor/donations": { title: "My Donations", description: "Review verified donation records." },
  "/donor/history": { title: "Donation History", description: "Review and export your donation history." },
  "/donor/emergency": { title: "Emergency Requests", description: "View urgent donor mobilisation requests." },
  "/donor/rewards": { title: "Rewards", description: "Track donor milestones and rewards." },
  "/donor/profile": { title: "Donor Profile", description: "Update donor contact and profile details." },
};

const input = "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-[#8f1220] focus:bg-white focus:ring-4 focus:ring-[#8f1220]/10";

function Shell({ meta, children }) {
  const navigate = useNavigate();
  return <div className="space-y-6 pb-8">
    <div className="flex flex-wrap items-end justify-between gap-4">
      <div><button onClick={() => navigate(-1)} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-[#8f1220]"><FaArrowLeft /> Back</button><h1 className="text-3xl font-bold text-slate-900">{meta.title}</h1><p className="mt-1 max-w-3xl text-slate-500">{meta.description}</p></div>
    </div>{children}
  </div>;
}

function DataTable({ columns, rows, empty = "No records found." }) {
  return <div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr>{columns.map((column) => <th key={column} className="px-5 py-3">{column}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td colSpan={columns.length} className="px-5 py-10 text-center text-sm text-slate-500">{empty}</td></tr>}</tbody></table></div>;
}

function AdminModule({ path }) {
  const { adminUsers = [], setAdminUsers, hospitals = [], setHospitals, auditLogs = [], setAuditLogs } = useAppState();
  const [query, setQuery] = useState("");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState(ROLES.HOSPITAL_STAFF);
  const [hospitalName, setHospitalName] = useState("");
  const [saving, setSaving] = useState(false);
  const addUser = (e) => { e.preventDefault(); if (!name.trim() || !email.trim()) return; const record = { id: Date.now(), name: name.trim(), email: email.trim(), role, hospital: role === ROLES.HOSPITAL_STAFF ? "Unassigned" : "UMULOPA", status: "Pending" }; setAdminUsers?.((v) => [...v, record]); setAuditLogs?.((v) => [{ id: Date.now(), event: "User created", detail: `${record.name} account created`, time: new Date().toLocaleString() }, ...v]); setName(""); setEmail(""); setSaving(true); setTimeout(() => setSaving(false), 400); };
  if (path === "/admin/users") return <Shell meta={catalog[path]}><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><form onSubmit={addUser} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Create account</h2><div className="mt-4 space-y-3"><input className={input} value={name} onChange={(e) => setName(e.target.value)} placeholder="Full name" required /><input className={input} type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email address" required /><select className={input} value={role} onChange={(e) => setRole(e.target.value)}><option value={ROLES.HOSPITAL_STAFF}>Hospital Staff</option><option value={ROLES.REGIONAL_CENTRE}>Regional Centre</option><option value={ROLES.DONOR}>Donor</option><option value={ROLES.SYSTEM_ADMIN}>System Administrator</option></select></div><button disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaUserPlus /> {saving ? "Saving…" : "Create user"}</button></form><div><div className="mb-3 flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3"><FaSearch className="text-slate-400" /><input className="w-full py-2.5 text-sm outline-none" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search users" /></div><DataTable columns={["User", "Role", "Hospital", "Status", "Action"]} rows={adminUsers.filter((u) => `${u.name} ${u.email}`.toLowerCase().includes(query.toLowerCase())).map((u) => <tr key={u.id} className="border-b border-slate-50"><td className="px-5 py-4"><b>{u.name}</b><p className="text-xs text-slate-500">{u.email}</p></td><td className="px-5 py-4 text-sm">{roleLabels[normaliseRole(u.role)] || u.role}</td><td className="px-5 py-4 text-sm">{u.hospital}</td><td className="px-5 py-4"><StatusBadge status={u.status === "Active" ? "success" : "warning"}>{u.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={() => setAdminUsers?.((v) => v.map((x) => x.id === u.id ? { ...x, status: x.status === "Active" ? "Suspended" : "Active" } : x))} className="text-sm font-semibold text-[#8f1220]">{u.status === "Active" ? "Suspend" : "Activate"}</button></td></tr>)} /></div></div></Shell>;
  if (path === "/admin/hospitals") return <Shell meta={catalog[path]}><form onSubmit={(e) => { e.preventDefault(); if (!hospitalName.trim()) return; const h = { id: Date.now(), name: hospitalName.trim(), status: "Active", units: 0 }; setHospitals?.((v) => [...v, h]); setAuditLogs?.((v) => [{ id: Date.now(), event: "Hospital added", detail: h.name, time: new Date().toLocaleString() }, ...v]); setHospitalName(""); }} className="flex max-w-xl gap-2 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><input className={input} value={hospitalName} onChange={(e) => setHospitalName(e.target.value)} placeholder="Hospital name" required /><button className="shrink-0 rounded-xl bg-[#8f1220] px-4 text-sm font-semibold text-white"><FaPlus /></button></form><DataTable columns={["Hospital", "Units", "Status", "Action"]} rows={hospitals.map((h) => <tr key={h.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{h.name}</td><td className="px-5 py-4">{h.units ?? 0}</td><td className="px-5 py-4"><StatusBadge status="success">{h.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={() => setHospitals?.((v) => v.map((x) => x.id === h.id ? { ...x, status: x.status === "Active" ? "Suspended" : "Active" } : x))} className="text-sm font-semibold text-[#8f1220]">Toggle status</button></td></tr>)} /></Shell>;
  if (path === "/admin/audit-logs") return <Shell meta={catalog[path]}><DataTable columns={["Event", "Detail", "Time"]} rows={auditLogs.map((x) => <tr key={x.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{x.event}</td><td className="px-5 py-4 text-sm text-slate-600">{x.detail}</td><td className="px-5 py-4 text-xs text-slate-500">{x.time}</td></tr>)} /></Shell>;
  if (path === "/admin/roles") return <Shell meta={catalog[path]}><DataTable columns={["Role", "Purpose", "Access"]} rows={Object.values(ROLES).map((r) => <tr key={r} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{roleLabels[r]}</td><td className="px-5 py-4 text-sm text-slate-600">{r === "admin" ? "Platform administration" : r === "regional" ? "Regional blood centre operations" : r === "staff" ? "Hospital clinical operations" : "Donor self-service"}</td><td className="px-5 py-4"><StatusBadge status="info">Protected</StatusBadge></td></tr>)} /></Shell>;
  if (path === "/admin/permissions") return <PermissionsPanel audit={(detail) => setAuditLogs?.((v) => [{ id: Date.now(), event: "Permission action", detail, time: new Date().toLocaleString() }, ...v])} />;
  if (path === "/admin/system-health") return <Shell meta={catalog[path]}><div className="grid gap-4 md:grid-cols-3">{["Frontend", "Application state", "Routing"].map((s) => <div key={s} className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><p className="font-bold text-emerald-900">{s}</p><p className="mt-2 text-sm text-emerald-800">Operational</p><StatusBadge status="success">Healthy</StatusBadge></div>)}</div></Shell>;
  if (path === "/admin/backup") return <Shell meta={catalog[path]}><BackupPanel onAudit={(detail) => setAuditLogs?.((v) => [{ id: Date.now(), event: "Backup action", detail, time: new Date().toLocaleString() }, ...v])} /></Shell>;
  if (path === "/admin/reports") return <Shell meta={catalog[path]}><ReportPanel rows={adminUsers} filename="umulopa-platform-users.csv" /></Shell>;
  if (path === "/admin/settings") return <Shell meta={catalog[path]}><SettingsPanel /></Shell>;
  return null;
}

function PermissionsPanel({ audit }) {
  const navigate = useNavigate();
  const permissions = [
    { name: "Manage users", description: "Create, activate, suspend and review platform accounts.", path: "/admin/users", action: "Manage users" },
    { name: "Manage hospitals", description: "Add connected facilities and control their network status.", path: "/admin/hospitals", action: "Manage hospitals" },
    { name: "Approve requests", description: "Review urgent and routine blood requests at the operational level.", path: "/regional/emergency", action: "Review requests" },
    { name: "Adjust stock", description: "Increase or decrease regional blood inventory and monitor thresholds.", path: "/regional/inventory", action: "Adjust stock" },
    { name: "View reports", description: "Export current platform records and operational reports.", path: "/admin/reports", action: "View reports" },
    { name: "Run backups", description: "Create an application-state snapshot and record the backup event.", path: "/admin/backup", action: "Run backup" },
  ];
  return <Shell meta={catalog["/admin/permissions"]}>
    <div className="grid gap-4 md:grid-cols-2">
      {permissions.map((permission) => <article key={permission.name} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">
        <div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-900">{permission.name}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{permission.description}</p></div><FaShieldAlt className="shrink-0 text-[#8f1220]" /></div>
        <div className="mt-4 flex flex-wrap items-center gap-2"><StatusBadge status="success">Protected</StatusBadge><button type="button" onClick={() => { audit?.(`${permission.name} opened by System Administrator`); navigate(permission.path); }} className="ml-auto rounded-xl bg-[#8f1220] px-3 py-2 text-xs font-semibold text-white hover:bg-[#720d18]">{permission.action}</button></div>
      </article>)}
    </div>
  </Shell>;
}

function BackupPanel({ onAudit }) { const [status, setStatus] = useState("Ready"); return <div className="max-w-xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Backup control</h2><p className="mt-2 text-sm text-slate-500">Create a frontend snapshot of the current application state.</p><button onClick={() => { setStatus("Backup completed"); onAudit?.("Manual application-state backup completed"); }} className="mt-5 rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaSave className="mr-2 inline" /> Run backup</button><p className="mt-3 text-sm font-semibold text-emerald-700">{status}</p></div>; }
function ReportPanel({ rows, filename }) { return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Export report</h2><p className="mt-2 text-sm text-slate-500">Export the current records to CSV for review or submission.</p><button onClick={() => exportToCsv(filename, Object.keys(rows[0] || {}).map((key) => ({ key, label: key })), rows)} className="mt-5 rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaDownload className="mr-2 inline" /> Export CSV</button></div>; }
function SettingsPanel() { const [saved, setSaved] = useState(false); const [mfa, setMfa] = useState(true); return <div className="max-w-2xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm space-y-5"><label className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><span><b>Require MFA</b><small className="block text-xs text-slate-500">Protect privileged accounts.</small></span><input type="checkbox" checked={mfa} onChange={(e) => setMfa(e.target.checked)} /></label><button onClick={() => setSaved(true)} className="rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaSave className="mr-2 inline" /> Save settings</button>{saved && <p className="text-sm font-semibold text-emerald-700">Settings saved successfully.</p>}</div>; }

function RegionalModule({ path }) {
  const { stock = [], setStock, bloodRequests = [], setBloodRequests, hospitals = [], transfers = [], setTransfers, setAuditLogs } = useAppState();
  if (path === "/regional/inventory") return <Shell meta={catalog[path]}><div className="grid gap-4 sm:grid-cols-3">{stock.map((s) => <div key={s.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs uppercase text-slate-400">{s.type}</p><p className="mt-2 text-3xl font-bold">{s.quantity}</p><p className="text-xs text-slate-500">Threshold {s.threshold}</p><div className="mt-3 flex gap-2"><button onClick={() => setStock?.((v) => v.map((x) => x.id === s.id ? { ...x, quantity: x.quantity + 1 } : x))} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-sm font-bold text-emerald-700">+1</button><button onClick={() => setStock?.((v) => v.map((x) => x.id === s.id ? { ...x, quantity: Math.max(0, x.quantity - 1) } : x))} className="rounded-lg bg-rose-50 px-3 py-1.5 text-sm font-bold text-rose-700">-1</button></div></div>)}</div><div className="mt-6"><DataTable columns={["Blood group", "Available", "Threshold", "Status"]} rows={stock.map((s) => <tr key={s.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{s.type}</td><td className="px-5 py-4">{s.quantity}</td><td className="px-5 py-4">{s.threshold}</td><td className="px-5 py-4"><StatusBadge status={s.quantity < s.threshold ? "danger" : "success"}>{s.quantity < s.threshold ? "Low" : "Adequate"}</StatusBadge></td></tr>)}/></div></Shell>;
  if (path === "/regional/distribution" || path === "/regional/emergency") return <Shell meta={catalog[path]}><DataTable columns={["Patient / request", "Group", "Units", "Urgency", "Status", "Action"]} rows={bloodRequests.map((r) => <tr key={r.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{r.patient}</td><td className="px-5 py-4">{r.bloodType}</td><td className="px-5 py-4">{r.units}</td><td className="px-5 py-4">{r.urgency}</td><td className="px-5 py-4"><StatusBadge status={r.status === "Approved" ? "success" : r.urgency === "High" ? "danger" : "warning"}>{r.status}</StatusBadge></td><td className="px-5 py-4 flex gap-2"><button onClick={() => setBloodRequests?.((v) => v.map((x) => x.id === r.id ? { ...x, status: "Approved" } : x))} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><FaCheck /></button><button onClick={() => setBloodRequests?.((v) => v.map((x) => x.id === r.id ? { ...x, status: "Rejected" } : x))} className="rounded-lg bg-rose-50 px-3 py-1.5 text-xs font-bold text-rose-700">Reject</button></td></tr>)}/></Shell>;
  if (path === "/regional/hospitals") return <Shell meta={catalog[path]}><DataTable columns={["Hospital", "Units", "Status"]} rows={hospitals.map((h) => <tr key={h.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{h.name}</td><td className="px-5 py-4">{h.units ?? 0}</td><td className="px-5 py-4"><StatusBadge status="success">{h.status}</StatusBadge></td></tr>)}/></Shell>;
  if (path === "/regional/transfers") return <Shell meta={catalog[path]}><TransferPanel transfers={transfers} setTransfers={setTransfers} onAudit={(detail) => setAuditLogs?.((v) => [{ id: Date.now(), event: "Transfer action", detail, time: new Date().toLocaleString() }, ...v])} /></Shell>;
  if (path === "/regional/analytics") return <Shell meta={catalog[path]}><div className="grid gap-4 md:grid-cols-4">{[{l:"Requests",v:bloodRequests.length},{l:"Approved",v:bloodRequests.filter(x=>x.status==="Approved").length},{l:"Units in stock",v:stock.reduce((a,x)=>a+x.quantity,0)},{l:"Hospitals",v:hospitals.length}].map(x=><div key={x.l} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">{x.l}</p><p className="mt-2 text-3xl font-bold">{x.v}</p></div>)}</div></Shell>;
  if (path === "/regional/reports") return <Shell meta={catalog[path]}><ReportPanel rows={bloodRequests} filename="umulopa-regional-requests.csv" /></Shell>;
  if (path === "/regional/settings") return <Shell meta={catalog[path]}><SettingsPanel /></Shell>;
  return null;
}
function TransferPanel({ transfers = [], setTransfers, onAudit }) { const [hospital, setHospital] = useState(""); const [units, setUnits] = useState(1); return <div className="space-y-6"><form onSubmit={(e) => { e.preventDefault(); if (!hospital) return; const t={id:Date.now(),hospital,blood:"O+",units:Number(units),status:"Planned",time:new Date().toLocaleTimeString()}; setTransfers?.((v)=>[t,...v]); onAudit?.(`Transfer created to ${hospital}`); setHospital(""); }} className="max-w-xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Create transfer</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className={input} value={hospital} onChange={e=>setHospital(e.target.value)} placeholder="Destination hospital" required/><input className={input} type="number" min="1" value={units} onChange={e=>setUnits(e.target.value)} /></div><button className="mt-4 rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaTruck className="mr-2 inline"/>Create transfer</button></form><DataTable columns={["Destination","Blood","Units","Status","Action"]} rows={transfers.map(t=><tr key={t.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{t.hospital}</td><td className="px-5 py-4">{t.blood}</td><td className="px-5 py-4">{t.units}</td><td className="px-5 py-4"><StatusBadge status={t.status === "Completed" ? "success" : "info"}>{t.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={()=>setTransfers?.(v=>v.map(x=>x.id===t.id?{...x,status:x.status==="Planned"?"Dispatched":x.status==="Dispatched"?"Completed":"Completed"}:x))} className="text-sm font-semibold text-[#8f1220]">Advance status</button></td></tr>)}/></div>; }

function StaffEmergency() { const { bloodRequests=[], setBloodRequests }=useAppState(); return <Shell meta={catalog["/staff/emergency"]}><div className="rounded-3xl border border-red-200 bg-red-50 p-5"><p className="font-bold text-red-900">Emergency workflow</p><p className="mt-1 text-sm text-red-800">Escalate high-priority requests to the regional centre.</p></div><DataTable columns={["Patient","Blood","Units","Urgency","Status","Action"]} rows={bloodRequests.map(r=><tr key={r.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{r.patient}</td><td className="px-5 py-4">{r.bloodType}</td><td className="px-5 py-4">{r.units}</td><td className="px-5 py-4">{r.urgency}</td><td className="px-5 py-4"><StatusBadge status={r.status === "Approved" ? "success" : "warning"}>{r.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={()=>setBloodRequests?.(v=>v.map(x=>x.id===r.id?{...x,status:"Escalated"}:x))} className="text-sm font-semibold text-[#8f1220]">Escalate</button></td></tr>)}/></Shell>; }

function DonorModule({ path }) { const { donors=[], setDonors, appointments=[], setAppointments, setNotifications }=useAppState(); const current=donors[0]||{id:1,name:"Donor",bloodType:"O+"}; const [date,setDate]=useState(""); const [profile,setProfile]=useState(current.name); if(path==="/donor/donate") return <Shell meta={catalog[path]}><form onSubmit={e=>{e.preventDefault(); if(!date)return; const a={id:Date.now(),date,centre:"Kitwe Donor Centre",status:"Pending",donor:current.name}; setAppointments?.(v=>[a,...v]); setNotifications?.(v=>[`${current.name} requested a donation appointment`,...v]); setDate("");}} className="max-w-xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Request a donation appointment</h2><p className="mt-1 text-sm text-slate-500">Choose a date and the donor centre will confirm availability.</p><input className={`${input} mt-4`} type="date" value={date} onChange={e=>setDate(e.target.value)} required/><button className="mt-4 rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaTint className="mr-2 inline"/>Submit request</button></form></Shell>;
  if(path==="/donor/appointments") return <Shell meta={catalog[path]}><DataTable columns={["Date","Centre","Status","Action"]} rows={appointments.map(a=><tr key={a.id} className="border-b border-slate-50"><td className="px-5 py-4 font-semibold">{a.date}</td><td className="px-5 py-4">{a.centre}</td><td className="px-5 py-4"><StatusBadge status={a.status==="Confirmed"?"success":"warning"}>{a.status}</StatusBadge></td><td className="px-5 py-4"><button onClick={()=>setAppointments?.(v=>v.map(x=>x.id===a.id?{...x,status:x.status==="Pending"?"Confirmed":"Cancelled"}:x))} className="text-sm font-semibold text-[#8f1220]">{a.status==="Pending"?"Confirm":"Cancel"}</button></td></tr>)}/></Shell>;
  if(path==="/donor/donations"||path==="/donor/history") return <Shell meta={catalog[path]}><div className="mb-4 flex justify-end"><button onClick={()=>exportToCsv("donor-appointments.csv", [{ key: "date", label: "Date" }, { key: "centre", label: "Centre" }, { key: "status", label: "Status" }, { key: "donor", label: "Donor" }], appointments)} className="rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaDownload className="mr-2 inline"/>Export CSV</button></div><DataTable columns={["Date","Centre","Status","Donor"]} rows={appointments.map(a=><tr key={a.id} className="border-b border-slate-50"><td className="px-5 py-4">{a.date}</td><td className="px-5 py-4">{a.centre}</td><td className="px-5 py-4"><StatusBadge status="success">{a.status}</StatusBadge></td><td className="px-5 py-4">{a.donor}</td></tr>)}/></Shell>;
  if(path==="/donor/emergency") {
    const { emergencyResponses = [], setEmergencyResponses, setAuditLogs } = useAppState();
    const response = emergencyResponses.find((x) => x.donorId === current.id && x.requestId === "KTH-O+-48H");
    const respond = () => {
      if (response) return;
      const record = { id: Date.now(), requestId: "KTH-O+-48H", donorId: current.id, donor: current.name, bloodType: current.bloodType || "O+", hospital: "Kitwe Teaching Hospital", status: "Responded", respondedAt: new Date().toLocaleString() };
      const appointment = { id: Date.now() + 1, date: "Within 48 hours", centre: "Kitwe Teaching Hospital", status: "Emergency Response", donor: current.name, emergency: true, requestId: record.requestId };
      setEmergencyResponses?.((v) => [record, ...v]);
      setAppointments?.((v) => [appointment, ...v]);
      setNotifications?.((v) => ["Emergency response sent to Kitwe Teaching Hospital.", ...v]);
      setAuditLogs?.((v) => [{ id: Date.now() + 2, event: "Emergency donor response", detail: `${current.name} volunteered for the O+ emergency request at Kitwe Teaching Hospital`, time: new Date().toLocaleString() }, ...v]);
    };
    return <Shell meta={catalog[path]}><div className="max-w-2xl rounded-3xl border border-amber-200 bg-amber-50 p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex rounded-full bg-amber-200 px-3 py-1 text-xs font-bold text-amber-900">URGENT · 48 HOURS</span><h2 className="mt-4 text-2xl font-bold text-amber-950">O+ donors needed</h2><p className="mt-2 leading-6 text-amber-900">Kitwe Teaching Hospital needs O+ donors within the next 48 hours.</p><p className="mt-2 text-sm text-amber-800">Your response will be recorded and an emergency donation appointment will be created in your appointments.</p></div><FaTint className="text-3xl text-[#8f1220]" /></div><button type="button" disabled={Boolean(response)} onClick={respond} className={`mt-6 rounded-xl px-5 py-3 text-sm font-semibold text-white ${response ? "cursor-not-allowed bg-emerald-600" : "bg-[#8f1220] hover:bg-[#720d18]"}`}>{response ? "Response sent ✓" : "I can donate"}</button>{response && <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><b>Thank you.</b> Your availability has been sent to Kitwe Teaching Hospital and added to your appointments.</div>}</div></Shell>;
  }
  if(path==="/donor/rewards") return <Shell meta={catalog[path]}><div className="grid gap-4 sm:grid-cols-3">{[["Community Lifesaver","8 donations"],["Reliable Donor","5 appointments"],["Emergency Helper","1 emergency response"]].map(([a,b])=><div key={a} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="font-bold">{a}</p><p className="mt-2 text-sm text-slate-500">{b}</p><StatusBadge status="success">Earned</StatusBadge></div>)}</div></Shell>;
  if(path==="/donor/profile") return <Shell meta={catalog[path]}><form onSubmit={e=>{e.preventDefault(); setDonors?.(v=>v.map(x=>x.id===current.id?{...x,name:profile}:x)); setNotifications?.(v=>["Donor profile updated successfully",...v]);}} className="max-w-xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><label className="block text-sm font-semibold">Full name<input className={`${input} mt-2`} value={profile} onChange={e=>setProfile(e.target.value)} required/></label><p className="mt-4 text-sm text-slate-500">Blood group: <b>{current.bloodType}</b></p><button className="mt-5 rounded-xl bg-[#8f1220] px-4 py-2.5 text-sm font-semibold text-white"><FaSave className="mr-2 inline"/>Save profile</button></form></Shell>;
  return null; }

export default function RoleModulePage() { const { pathname }=useLocation(); const meta=catalog[pathname]||{title:"Module",description:"Operational workspace"}; if(pathname.startsWith("/admin/")) return <AdminModule path={pathname}/>; if(pathname.startsWith("/regional/")) return <RegionalModule path={pathname}/>; if(pathname==="/staff/emergency") return <StaffEmergency/>; if(pathname.startsWith("/donor/")) return <DonorModule path={pathname}/>; return <Shell meta={meta}><div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><p className="text-slate-600">This module is connected to the application state and role-protected navigation.</p></div></Shell>; }
