import { useState } from "react";
import { NavLink } from "react-router-dom";
import { FaAmbulance, FaBars, FaChartLine, FaClipboardList, FaCog, FaHeartbeat, FaHome, FaHospital, FaKey, FaShieldAlt, FaTint, FaTruck, FaUserPlus, FaUsers, FaWarehouse } from "react-icons/fa";
import { getNavItemsForRole, normaliseRole, resolveDashboardLink, roleLabels, ROLES } from "../utils/roles";
import { useAppState } from "../context/useAppState";

const icons = { home: FaHome, userPlus: FaUserPlus, droplet: FaTint, heartbeat: FaHeartbeat, inventory: FaWarehouse, plus: FaUserPlus, users: FaUsers, file: FaClipboardList, chart: FaChartLine, alert: FaClipboardList, settings: FaCog, roles: FaKey, hospitals: FaHospital, permissions: FaShieldAlt, health: FaHeartbeat, backup: FaWarehouse, distribution: FaTint, emergency: FaAmbulance, transfers: FaTruck };
const adminItems = [{ to: "/admin", label: "Dashboard", icon: "home" }, { to: "/admin/users", label: "Users", icon: "users" }, { to: "/admin/roles", label: "Roles", icon: "roles" }, { to: "/admin/hospitals", label: "Hospitals", icon: "hospitals" }, { to: "/admin/permissions", label: "Permissions", icon: "permissions" }, { to: "/admin/audit-logs", label: "Audit Logs", icon: "file" }, { to: "/admin/reports", label: "Reports", icon: "chart" }, { to: "/admin/system-health", label: "System Health", icon: "health" }, { to: "/admin/settings", label: "Settings", icon: "settings" }, { to: "/admin/backup", label: "Backup", icon: "backup" }];
const regionalItems = [{ to: "/regional", label: "Regional Overview", icon: "home" }, { to: "/regional/inventory", label: "Blood Inventory", icon: "inventory" }, { to: "/regional/distribution", label: "Blood Distribution", icon: "distribution" }, { to: "/regional/hospitals", label: "Hospitals", icon: "hospitals" }, { to: "/regional/emergency", label: "Emergency Requests", icon: "emergency" }, { to: "/regional/transfers", label: "Transfers", icon: "transfers" }, { to: "/regional/analytics", label: "Analytics", icon: "chart" }, { to: "/regional/reports", label: "Reports", icon: "file" }, { to: "/regional/settings", label: "Settings", icon: "settings" }];
const staffItems = [{ to: "/staff", label: "Dashboard", icon: "home" }, { to: "/patients", label: "Patients", icon: "users" }, { to: "/patients/request", label: "Blood Requests", icon: "droplet" }, { to: "/patients/transfusions", label: "Transfusions", icon: "heartbeat" }, { to: "/inventory", label: "Blood Inventory", icon: "inventory" }, { to: "/donors", label: "Donor Registry", icon: "users" }, { to: "/staff/emergency", label: "Emergency Cases", icon: "emergency" }, { to: "/reports/weekly", label: "Reports", icon: "file" }];
const donorItems = [{ to: "/donor", label: "Dashboard", icon: "home" }, { to: "/donor/donate", label: "Donate Blood", icon: "droplet" }, { to: "/donor/appointments", label: "Appointments", icon: "file" }, { to: "/donor/donations", label: "My Donations", icon: "heartbeat" }, { to: "/donor/history", label: "Donation History", icon: "chart" }, { to: "/donor/emergency", label: "Emergency Requests", icon: "emergency" }, { to: "/donor/rewards", label: "Rewards", icon: "users" }, { to: "/donor/profile", label: "Profile", icon: "userPlus" }, { to: "/settings", label: "Settings", icon: "settings" }];
export default function Sidebar({ mobileOpen = false, onClose = () => {} }) {
  const [collapsed, setCollapsed] = useState(false); const { user } = useAppState(); const role = normaliseRole(user?.role); const items = role === ROLES.SYSTEM_ADMIN ? adminItems : role === ROLES.REGIONAL_CENTRE ? regionalItems : role === ROLES.HOSPITAL_STAFF ? staffItems : role === ROLES.DONOR ? donorItems : getNavItemsForRole(role);
  return <><div className={`fixed inset-0 z-30 bg-black/40 md:hidden ${mobileOpen ? "block" : "hidden"}`} onClick={onClose} />
    <aside className={`fixed left-0 top-0 z-40 flex h-full flex-col bg-[#6B0F1A] text-white shadow-lg transition-all md:static md:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full md:translate-x-0"} ${collapsed ? "w-20" : "w-64"}`}>
      <div className="flex items-center justify-between border-b border-white/10 px-4 py-4"><div className={collapsed ? "hidden" : "block"}><p className="font-bold">UMULOPA</p><p className="text-[10px] uppercase tracking-[.18em] text-white/65">Safe Blood Transfer</p></div><button onClick={() => setCollapsed((value) => !value)} className="rounded-xl p-2 hover:bg-white/10" aria-label="Toggle sidebar"><FaBars /></button></div>
      <nav className="flex-1 space-y-1 overflow-y-auto px-2 py-4">{items.map((item) => { if (item.section) return !collapsed && <p key={item.section} className="px-3 pt-4 text-[10px] font-semibold uppercase tracking-widest text-white/50">{item.section}</p>; const Icon = icons[item.icon] || FaHospital; return <NavLink key={item.to} to={resolveDashboardLink(role, item)} onClick={onClose} className={({ isActive }) => `flex items-center gap-3 rounded-2xl px-3 py-3 text-sm ${isActive ? "bg-white text-[#6B0F1A]" : "text-white/85 hover:bg-white/10"}`}><Icon /><span className={collapsed ? "hidden" : "block"}>{item.label}</span></NavLink>; })}</nav>
      {!collapsed && <div className="border-t border-white/10 p-4"><p className="text-sm font-semibold">{roleLabels[role]}</p><p className="mt-1 text-xs text-white/65">Secure workspace</p></div>}
    </aside></>;
}
